name: Minikube CI Test

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Deploy to Minikube

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest

    - name: Verify Minikube cluster
      run: kubectl get nodes

    - name: Build Docker image with Minikube
      run: |
        minikube image build -t local/example:latest .

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deploy/k8s.yaml
        kubectl rollout status deployment/example

    - name: Test Service via Curl
      run: |
        echo "Getting Minikube service URL"
        SERVICE_URL=$(minikube service example --url)
        echo "Service URL: $SERVICE_URL"
        curl $SERVICE_URL
